#spring:
#  application:
#    name: simplePay
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql:3306/show_tick?characterEncoding=utf-8
#    username: root
#    password: 123456
#
#  data:
#    redis:
#      host: localhost
#      port: 6379
#
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl